baseURL      = 'https://emptyarea.com/'
title        = 'Emptyarea'
theme        = 'emptyarea'
copyright    = 'Copyright © {year} Powered by '

# menu
[[menus.main]]
URL = '/'
name = 'Home'
weight = 1

[[menus.main]]
URL = '/work/'
name = 'Work'
weight = 2

[[menus.main]]
URL = '/about/'
name = 'About'
weight = 3

[[menus.main]]
URL = '/contact/'
name = 'Contact'
weight = 4


# default parameters
[params]
home = 'Home'
logo = '/img/logo-emptyarea.svg'
logo_light = '/img/logo-light.svg'
# contact info
email = 'taoguangc@gmail.com'
address = '125/A, CA Commercial Area, California, USA'
# meta description
author = 'Jeffrey Qian'
description = 'This is meta description'
# google analytics
google_analytics_id = '' # Your ID
# copyright

imageWidths = [1500, 900, 600]

[outputs]
    home = ['html']

[module]
    [module.hugoVersion]
        min = '0.128.0'
    [[module.mounts]]
        source = 'assets'
        target = 'assets'
    [[module.mounts]]
        source = 'content'
        target = 'content'
    [[module.mounts]]
        source       = 'hugo_stats.json'
        target       = 'assets/notwatching/hugo_stats.json'
        disableWatch = true